<?php 
/**
 * Main translation for the package (Spanish)
 */
return [
  'connectWithUs' => 'Conéctate con nosotros',
  'ourCompany' => 'Nuestra empresa',
  'mission' => 'Misión',
  'vision' => 'Visión',
  'contactUs' => 'Contáctanos',
  'contactInfo' => 'Información de contacto',
  'ubication' => 'Ubicación',
  'phones' => 'Teléfonos',
  'email' => 'Correo electrónico',
  'navigation' => 'Navegación',
  'firstName' => 'Nombre',
  'lastName' => 'Apellido',
  'company' => 'Empresa',
  'message' => 'Mensaje',
  'howDidYouFindUs' => 'Como Nos Encontraste?',
  'costumer' => 'Cliente',
  'store' => 'Tienda',
  'other' => 'Otro',
  'communicationPreference' => 'Como nos comunicamos contigo?',
  'callMe' => 'Llamada',
  'newsletter' => 'Boletín Informativo',
  'sendMessage' => 'Enviar Mensaje',
  'locateUsOnMap' => 'Localizanos en el mapa',
  'demoSlider1HeaderH1' => 'Material Design',
  'demoSlider1HeaderH2' => 'Diseño basado en la tendencia Material',
  'demoSlider2HeaderH1' => 'Diseño Responsivo',
  'demoSlider2HeaderH2' => 'Adaptado a cualquier dispositivo',  
  'demoSlider3HeaderH1' => 'Modifica fácilmente todo de tu sitio',
  'demoSlider3HeaderH2' => 'Puedes cambiar de manera rápida el diseño ( apariencia, textos, Imagenes), y extender nuevas funciones a tu sitio.',
  'demoSlider4HeaderH1' => '¿Deseas un diseño más personalizado?',
  'demoSlider4HeaderH2' => '¡Comunícate con nosotros!',
  'section1Message1' => '¡Ya tienes un buen comienzo!',
  'section1Message2' => 'Extiende facilmente tu sitio web, anexandole búsquedas de tus productos, carrito de compra, formularios de contacto, panel administrativo, etc. ¡Gracias a una buena estructura inicial!',
  'section1ButtonText' => '¡Da el siguiente paso!',
  'section2Card1Message1' =>  'Las mejores herramientas',
  'section2Card1Message2' =>  'Para que un sitio web exitoso, es necesario que sea fácilmente extensible y personalizable. Esto involucra tener una buena estructura que permita hacer cambios rápidamente.',
  'section2Card2Message1' =>  'Extiende Rápidamente',
  'section2Card2Message2' =>  'Gracias a las tecnologías usadas en tu sitio como el framework Laravel, no requerirás de personal con mucha experiencia en desarrollo web, si eres el dueño del negocio; o podrás desarrollar rapidamente y de manera organizada, si eres desarrollador.',
  'section2Card3Message1' =>  'Fácilmente Personalizable',
  'section2Card3Message2' =>  'Las tendencias de diseño ahora están a tu mano gracias al Framework de diseño MaterializeCss, por lo que podrás tener un sitio con un diseño pulcro y actual. Puedes buscar un diseñador para personalizar el diseño fácilmente.',
  'section3Message1' => 'Nuestros productos más destacados',
  'section3DetailMessage' => 'VER DETALLE',
  'section4Message1' => 'Te ofrecemos un servicio de calidad',
  'section4ButtonMessage' => '¡Contáctanos!',
  'section5Message1' => 'Nuestros Clientes',
  'section6Message1' => 'Redes Sociales',
  'products' => 'Productos',
  'ourProducts' => 'Nuestros productos',
  'menuProductCardMessage1' => 'Busca productos por categoría.',
  'category' => 'Categoría',
  'linkSeeProductText' => 'VER DETALLE',
  'companyName' => ' Nombre de la empresa',
  'companyDescription' => 'Descripción de la empresa.'


];