<?php 
/**
 * Main translation for the package (English)
 */
return [
  'connectWithUs' => 'Connect with us',
  'ourCompany' => 'Our company',
  'mission' => 'Mission',
  'vision' => 'Vision',
  'contactUs' => 'Contact us',
  'contactInfo' => 'Contact information',
  'ubication' => 'Locatization',
  'phones' => 'Phones',
  'email' => 'E-mail',
  'navigation' => 'Navigation',
  'firstName' => 'First Name',
  'lastName' => 'Last Name',
  'company' => 'Company',
  'message' => 'Message',
  'howDidYouFindUs' => 'How Did You Find Us?',
  'costumer' => 'Costumer',
  'store' => 'Store',
  'other' => 'Other',
  'communicationPreference' => 'Communication Preference',
  'callMe' => 'Call Me',
  'newsletter' => 'Newsletter',
  'sendMessage' => 'Send Message',
  'locateUsOnMap' => 'Locate us on map',
  'demoSlider1HeaderH1' => 'Material Design',
  'demoSlider1HeaderH2' => 'Design based on the fresh Material Design',
  'demoSlider2HeaderH1' => 'Resposive Design',
  'demoSlider2HeaderH2' => 'Looks great on every single device!',
  'demoSlider3HeaderH1' => 'Personalize your website easily',
  'demoSlider3HeaderH2' => 'You can quickly adapt your site and change it as you want ( appearance, texts, images), you can also extend new features.',
  'demoSlider4HeaderH1' => 'Want a customized design?',
  'demoSlider4HeaderH2' => 'Contact us!',
  'section1Message1' => 'There you go, you\'re on your way!',
  'section1Message2' => 'Now you can add new features to your website, such as: global and filtered product search, shopping cart, contact form, admin panel, and so on. Thanks to this great starter project template!',
  'section1ButtonText' => 'Next step',
  'section2Card1Message1' =>  'Best tools',
  'section2Card1Message2' =>  'We\'re using the best programming tools for a medium-sized web project: Laravel framework, Jquery, ReactJS. These will make your project a Slam Dunk!',
  'section2Card2Message1' =>  'Quickly extensible',
  'section2Card2Message2' =>  'This is not the end of the road!. Thanks to the use of the best tools and the given project structure, developers can add new features easily.',
  'section2Card3Message1' =>  'Highly customizable',
  'section2Card3Message2' =>  'Not attached to the design whatsoever!, you can arguably find a web designer and change your website appearance.',
  'section3Message1' => 'Best Products',
  'section3DetailMessage' => 'CHECK IT OUT',
  'section4Message1' => 'We strive to offer you high quality service',
  'section4ButtonMessage' => 'Get in touch!',
  'section5Message1' => 'Our Clients',
  'section6Message1' => 'Social Network',
  'products' => 'Products',
  'ourProducts' => 'Our products',
  'menuProductCardMessage1' => 'Look for products by category.',
  'category' => 'Category',
  'linkSeeProductText' => 'CHECK IT OUT',
  'companyName' => 'Company Name',
  'companyDescription' => 'Company description.'


];